"""Write CRM-registered organization DIDs into Asterisk generated dialplan."""
from __future__ import annotations

import logging
import os
import subprocess
from pathlib import Path
from typing import Iterable

logger = logging.getLogger(__name__)

ASTERISK_GENERATED_DIR = Path(
    os.getenv("ASTERISK_GENERATED_DIR", "/app/asterisk/generated")
)
ORG_DIDS_CONF = "org-dids.conf"
ASTERISK_CONTAINER = os.getenv("ASTERISK_CONTAINER_NAME", "asterisk")


def _did_exten_variants(did: str) -> list[str]:
    digits = did.lstrip("+")
    variants = [digits, f"+{digits}"]
    seen: set[str] = set()
    out: list[str] = []
    for v in variants:
        if v not in seen:
            seen.add(v)
            out.append(v)
    return out


def write_org_dids_conf(organizations: Iterable) -> Path:
    """Regenerate org-dids.conf from active organizations."""
    ASTERISK_GENERATED_DIR.mkdir(parents=True, exist_ok=True)
    path = ASTERISK_GENERATED_DIR / ORG_DIDS_CONF
    lines = [
        "; Auto-generated by Aura CRM — do not edit manually",
        "; Reload: docker exec asterisk asterisk -rx \"dialplan reload\"",
    ]
    count = 0
    for org in organizations:
        if not getattr(org, "is_active", True):
            continue
        did = getattr(org, "did", None)
        name = getattr(org, "name", "org")
        if not did:
            continue
        for exten in _did_exten_variants(str(did)):
            lines.extend(
                [
                    f"exten => {exten},1,NoOp(CRM org {name} DID {exten})",
                    " same => n,Stasis(gemini-agent)",
                    " same => n,Hangup()",
                    "",
                ]
            )
            count += 1
    path.write_text("\n".join(lines), encoding="utf-8")
    logger.info("Wrote %s (%d dialplan entries)", path, count)
    return path


def reload_asterisk_dialplan() -> dict:
    """Best-effort dialplan reload when docker CLI is available."""
    try:
        result = subprocess.run(
            [
                "docker",
                "exec",
                ASTERISK_CONTAINER,
                "asterisk",
                "-rx",
                "dialplan reload",
            ],
            capture_output=True,
            text=True,
            timeout=15,
            check=False,
        )
        ok = result.returncode == 0
        if ok:
            logger.info("Asterisk dialplan reload succeeded")
        else:
            logger.warning(
                "Asterisk dialplan reload failed (rc=%s): %s",
                result.returncode,
                (result.stderr or result.stdout or "").strip(),
            )
        return {
            "reloaded": ok,
            "stdout": (result.stdout or "").strip(),
            "stderr": (result.stderr or "").strip(),
        }
    except FileNotFoundError:
        logger.info("docker CLI not available — dialplan file written; reload on asterisk restart")
        return {"reloaded": False, "note": "docker CLI not available"}
    except Exception as exc:
        logger.warning("Asterisk dialplan reload error: %s", exc)
        return {"reloaded": False, "error": str(exc)}


async def sync_organizations_to_asterisk(db) -> dict:
    from sqlalchemy import select

    from backend.db.models import Organization

    result = await db.execute(
        select(Organization).where(Organization.is_active.is_(True)).order_by(Organization.id)
    )
    orgs = list(result.scalars().all())
    path = write_org_dids_conf(orgs)
    reload = reload_asterisk_dialplan()
    return {
        "config_path": str(path),
        "organization_count": len(orgs),
        "asterisk": reload,
    }
