#!/usr/bin/env bash
# Write .host.env with LAN IP + SIP settings for Zoiper (phones on same Wi-Fi).
# Reads defaults/overrides from .env; auto-detects IP when EXTERNAL_IP=auto or unset.
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
ENV_FILE="$ROOT/.env"
HOST_ENV="$ROOT/.host.env"

read_env() {
  local key="$1"
  local default="${2:-}"
  if [ ! -f "$ENV_FILE" ]; then
    echo "$default"
    return
  fi
  local line raw
  line=$(grep -E "^${key}=" "$ENV_FILE" 2>/dev/null | tail -1 | cut -d= -f2- || true)
  raw="${line%$'\r'}"
  raw="${raw#\"}"; raw="${raw%\"}"
  raw="${raw#\'}"; raw="${raw%\'}"
  if [ -n "$raw" ]; then
    echo "$raw"
  else
    echo "$default"
  fi
}

detect_lan_ip() {
  local ip=""
  ip=$(ip -4 route get 1.1.1.1 2>/dev/null | awk '{for (i=1;i<=NF;i++) if ($i=="src") {print $(i+1); exit}}')
  if [ -z "$ip" ]; then
    ip=$(hostname -I 2>/dev/null | awk '{print $1}')
  fi
  echo "$ip"
}

OLD_IP=""
if [ -f "$HOST_ENV" ]; then
  OLD_IP=$(grep -E '^EXTERNAL_IP=' "$HOST_ENV" 2>/dev/null | tail -1 | cut -d= -f2- || true)
fi

# EXTERNAL_IP=auto (default) | fixed IPv4 e.g. 172.17.1.130 | empty = auto
EXTERNAL_IP_CFG=$(read_env EXTERNAL_IP "auto")
if [ -z "$EXTERNAL_IP_CFG" ] || [ "$EXTERNAL_IP_CFG" = "auto" ]; then
  IP=$(detect_lan_ip)
  IP_SOURCE="auto-detected"
else
  IP="$EXTERNAL_IP_CFG"
  IP_SOURCE="from .env"
fi

if [ -z "$IP" ]; then
  echo "ERROR: could not detect LAN IP. Set EXTERNAL_IP=your.pc.ip in .env" >&2
  exit 1
fi

SIP_PORT=$(read_env SIP_PORT "5060")
SIP_USER=$(read_env SIP_USER "1000")
SIP_PASS=$(read_env SIP_PASS "1000pass")
SIP_USER_1001=$(read_env SIP_USER_1001 "1001")
SIP_PASS_1001=$(read_env SIP_PASS_1001 "1001pass")
SIP_CODEC=$(read_env SIP_CODEC "PCMU")

IP_CHANGED=0
if [ -n "$OLD_IP" ] && [ "$OLD_IP" != "$IP" ]; then
  IP_CHANGED=1
  echo "LAN IP changed: ${OLD_IP} -> ${IP} (Asterisk will be recreated if running)"
fi

cat > "$HOST_ENV" <<EOF
# Generated by scripts/ensure-host-env.sh — re-run ./start.sh to refresh (do not edit)
# Resolved LAN address for Zoiper + Asterisk NAT
EXTERNAL_IP=${IP}
SIP_EXTERNAL_IP=${IP}
EXTERNAL_IP_MODE=$([ "$EXTERNAL_IP_CFG" = "auto" ] || [ -z "$EXTERNAL_IP_CFG" ] && echo auto || echo fixed)
IP_CHANGED=${IP_CHANGED}
SIP_PORT=${SIP_PORT}
SIP_USER=${SIP_USER}
SIP_PASS=${SIP_PASS}
SIP_USER_1001=${SIP_USER_1001}
SIP_PASS_1001=${SIP_PASS_1001}
SIP_CODEC=${SIP_CODEC}
EOF

echo "Wrote ${HOST_ENV}"
echo "  EXTERNAL_IP=${IP} (${IP_SOURCE})"
echo "  SIP server for Zoiper: ${IP}:${SIP_PORT} UDP — user ${SIP_USER}"
